export const CARDDECK = [
  // "airplane",
  "amazonka",
  // "greece",
  // "parashuts",
  // "venice",
  // "italy",
  "road",
  // "baunti",
  "bluewater",
  // "boat",
  // "break",
  // "bridge",
  // "camp",
  // "carhome",
  // "castle",
  // "china",
  // "church",
  // "ecuador",
  // "greece_sea",
  // "hot",
  // "india",
  "islands",
  // "japan",
  // "kimono",
  // "lake",
  // "lighthouse",
  // "map",
  "moscow",
  // "mountain",
  // "petra",
  // "portu",
  // "rainy-city",
  // "roadtrip",
  // "searoad",
  // "seaside",
  // "train",
  // "water-village",
  "waterline",
  // "window",
  // "yalta"
];

export default CARDDECK;
